
# Site settings
title: Sun Zhanhong, Dexter
name: Sun Zhanhong, Dexter
subtitle: Research Engineer
email: e0575916@u.nus.edu
description: >
  Research Engineer
baseurl: ""
url: "https://DexterSun.github.io/"
github_username:  DexterSun
disqus_baseurl: "https://DexterSun.github.io/"
disqus_shortname: https-DexterSun-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Sun Zhanhong, Dexter"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/DexterSun
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Dexter Sun
    url: https://www.linkedin.cn/in/dexter-sun-0096a81a8/
    desc: Connect with me on LinkedIn
    share: true
